internal:
  tables:
    accepted: tornado_usa
    rejected: tornado_usa_rejects
  fields:
    - name: year
      ptype: smallint
      dtype: int16[pyarrow]
      nullable: false
      unique: false
    - name: month
      ptype: smallint
      dtype: int8[pyarrow] # this works because month will range from 1-12
      nullable: false
      unique: false
    - name: day
      ptype: smallint
      dtype: int8[pyarrow] # this works because day will range from 0-31
      nullable: false
      unique: false
    - name: date
      ptype: date
      dtype: date32[pyarrow]
      nullable: false
      unique: false
    - name: state
      ptype: text
      dtype: string[pyarrow]
      nullable: false
      unique: false
    - name: magnitude
      ptype: integer
      dtype: int8[pyarrow]
      nullable: false
      unique: false
    - name: injury_count
      ptype: integer
      dtype: int16[pyarrow]
      nullable: false
      unique: false
    - name: fatality_count
      ptype: integer
      dtype: int16[pyarrow]
      nullable: false
      unique: false
    - name: latitude_start
      ptype: real
      dtype: float32[pyarrow]
      nullable: false
      unique: false
    - name: latitude_end
      ptype: real
      dtype: float32[pyarrow]
      nullable: false
      unique: false
    - name: longitude_start
      ptype: real
      dtype: float32[pyarrow]
      nullable: false
      unique: false
    - name: longitude_end
      ptype: real
      dtype: float32[pyarrow]
      nullable: false
      unique: false
    - name: length_miles
      ptype: real
      dtype: float32[pyarrow]
      nullable: false
      unique: false
    - name: width_yards
      ptype: smallint
      dtype: int16[pyarrow]
      nullable: false
      unique: false
external:
  sources:
    - path: data/tornado_usa.csv
      format: csv
      fields:
        - source_name: yr
          source_dtype: "int16[pyarrow]"
          target_name: year
        - source_name: mo
          source_dtype: "int8[pyarrow]"
          target_name: month
        - source_name: dy
          source_dtype: "int8[pyarrow]"
          target_name: day
        - source_name: date
          source_dtype: "date32[pyarrow]"
          target_name: date
        - source_name: st
          source_dtype: "string[pyarrow]"
          target_name: state
        - source_name: mag
          source_dtype: "int8[pyarrow]"
          target_name: magnitude
        - source_name: inj
          source_dtype: "int16[pyarrow]"
          target_name: injury_count
        - source_name: fat
          source_dtype: "int16[pyarrow]"
          target_name: fatality_count
        - source_name: slat
          source_dtype: "float32[pyarrow]"
          target_name: latitude_start
        - source_name: slon
          source_dtype: "float32[pyarrow]"
          target_name: longitude_start
        - source_name: elat
          source_dtype: "float32[pyarrow]"
          target_name: latitude_end
        - source_name: elon
          source_dtype: "float32[pyarrow]"
          target_name: longitude_end
        - source_name: len
          source_dtype: "float32[pyarrow]"
          target_name: length_miles
        - source_name: wid
          target_name: width_yards
          source_dtype: "int16[pyarrow]"
