internal:
  tables:
    accepted: wildfire_global
    rejected: wildfire_global_rejects
  fields:
    - name: country
      ptype: text
      dtype: string[pyarrow]
      nullable: false
      unique: false
    - name: year
      ptype: smallint
      dtype: int16[pyarrow]
      nullable: false
      unique: false
    - name: month
      ptype: text
      dtype: string[pyarrow]
      nullable: false
      unique: false
    - name: region
      ptype: text
      dtype: string[pyarrow]
      nullable: false
      unique: false
    - name: fires_count
      ptype: smallint
      dtype: int16[pyarrow]
      nullable: false
      unique: false
    - name: burned_area_hectares
      ptype: integer
      dtype: int16[pyarrow]
      nullable: false
      unique: false
    - name: cause
      ptype: text
      dtype: string[pyarrow]
      nullable: false
      unique: false
    - name: temperature_celsius
      ptype: smallint
      dtype: int8[pyarrow]
      nullable: false
      unique: false
    - name: humidity_percent
      ptype: smallint
      dtype: int8[pyarrow]
      nullable: false
      unique: false
    - name: wind_speed_kmh
      ptype: smallint
      dtype: int8[pyarrow]
      nullable: false
      unique: false
external:
  sources:
    - path: data/wildfire_global.csv
      format: csv
      fields:
      - source_name: Country
        target_name: country
      - source_name: Year
        target_name: year
      - source_name: Month
        target_name: month
      - source_name: Region
        target_name: region
      - source_name: Fires_Count
        target_name: fires_count
      - source_name: Burned_Area_Hectares
        target_name: burned_area_hectares
      - source_name: Cause
        target_name: cause
      - source_name: Temperature_C
        target_name: temperature_celsius
      - source_name: Humidity_Percent
        target_name: humidity_percent
      - source_name: Wind_Speed_kmh
        target_name: wind_speed_kmh
